version: '3.8'

services:
  custom-mysql:
    image: mysql
    container_name: jpa-specification-pagination
    ports:
      - '3305:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    volumes:
      - db:/var/lib/mysql

volumes:
  db: