version: '3.8'

services:
  custom-postgres:
    image: postgres
    container_name: jpa-specification-pagination
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: